### ISSUE TITLE
Possible bug or I'm confused.

### ISSUE THREAD

**Issue by falafflepotatoe** [akrymski/espresso.js#8]
Edit: NVM, you can close this....

it turns out it was my fault; if you use syntax
    for (i in arr){
        collection.push({id: i, ...})
        console.log(i, typeof i)
    }
you'll see JS uses a string type for index, and that breaks the collections update/find Fn's
## sorry.....

Hi I'm a little confused on Collection.set and Collection.push, can you tell me if this is a bug?

Anyway If you use collection.push({id: 9999, otherfield: 1234})
collection.set({id: anyid, ...}) no longer works... I assume this is because either you cannot set the ID from push, you cannot start above 0, or you cant use abritrary IDs from the backend ^_^.

1) What is the correct way to add an item to collection, .push()? Is it without specifying an id?
- I am using push({ id: 9999, otherfield: 1234, otherfield2: 1234 }), and i'm using Ids > 0 as my first item, I think this is causing the problem

2) What is the correct way to update one field of one item to that collection?
- If I do collection.set({ id: 1, field2: 'newdata'}), sometimes the entire object is replaced with this new smaller object (now only has these 2 fields) but usually nothing happens and .get(id) returns the old values

Maybe you can update the docs to be a little more clear? This is a great lib

**Comment by falafflepotatoe** [comment]
one more question for ya...

how do i do render something like this...

    render: func() { return {
        mylistdiv: { view: this.list, onclick: this.clickedlist }

view isnt the right attr name there im not sure what it is? of course "mylistdiv: this.list" renders fine...

**Comment by akrymski** [comment]
just wrap the list in another element:

<div ref=“wrapper”>
  <div ref=“mylistdiv”>

render: function() {
  return {
    wrapper: this.clickedlist
    mylistdiv: this.ist
}
